name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "111${{ secrets.DOCKER_PASSWORD }}"

      - name: SSH Deploy
        run: echo "222${{ secrets.SSH_PRIVATE_KEY }}"
